services:
  - type: web
    name: Hana portfolio
    env: node
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
